(async function(){
const res=await fetch('data.json');
const DATA=await res.json();
const{baseUrl,comingSoon,albums,comingSoonAlbum}=DATA;
const releaseDate=new Date(comingSoon);
const audio=new Audio();
const getAudio=(a,t)=>`${baseUrl}/m4a/${a.folder}/${t.file}`;
const getImage=a=>`${baseUrl}/images/${a.cover}`;
let playingAlbum=null,playingTrack=null,playingIdx=0,isPlaying=false,timer=null,viewedAlbum=null,countdownVisible=true;
const albumStates={};
const $=id=>document.getElementById(id);
const albumList=$('albumList'),tracklistWrap=$('tracklistWrap'),tracklist=$('tracklist'),tlTitle=$('tlTitle'),tlArtist=$('tlArtist'),tlBuyBtn=$('tlBuyBtn'),backBtn=$('backBtn'),headerBadge=$('headerBadge'),artImg=$('artImg'),countdownOverlay=$('countdownOverlay'),artBuyContainer=$('artBuyContainer'),artBuyBtn=$('artBuyBtn'),artBuyPrice=$('artBuyPrice'),cdDays=$('cdDays'),cdHours=$('cdHours'),cdMinutes=$('cdMinutes'),cdSeconds=$('cdSeconds'),csDate=$('csDate'),footerArt=$('footerArt'),footerTitle=$('footerTitle'),footerArtist=$('footerArtist'),footerFill=$('footerFill'),footerCur=$('footerCur'),footerTot=$('footerTot'),footerProgress=$('footerProgress'),footerPlay=$('footerPlay'),footerPrev=$('footerPrev'),footerNext=$('footerNext'),volumeSlider=$('volumeSlider'),volumeIcon=$('volumeIcon'),pmArt=$('pmArt'),pmTitle=$('pmTitle'),pmArtist=$('pmArtist'),pmPlay=$('pmPlay'),pmNext=$('pmNext'),pmExpand=$('pmExpand'),pf=$('playerFull'),pfArt=$('pfArt'),pfTitle=$('pfTitle'),pfArtist=$('pfArtist'),pfFill=$('pfFill'),pfCur=$('pfCur'),pfTot=$('pfTot'),pfProgress=$('pfProgress'),pfPlay=$('pfPlay'),pfPrev=$('pfPrev'),pfNext=$('pfNext'),pfClose=$('pfClose');
// HTC5 now playable — no isCS flag
const allAlbums=[...albums,{...comingSoonAlbum}];
audio.volume=.8;
if(volumeSlider){volumeSlider.value=.8;volumeSlider.addEventListener('input',function(){audio.volume=parseFloat(this.value);updateVolumeIcon()})}
function updateVolumeIcon(){if(!volumeIcon)return;const v=audio.volume;volumeIcon.className=v===0?'fas fa-volume-mute':v<.5?'fas fa-volume-down':'fas fa-volume-up'}
if(volumeIcon)volumeIcon.addEventListener('click',function(){if(audio.volume>0){audio.volume=0;if(volumeSlider)volumeSlider.value=0}else{audio.volume=.8;if(volumeSlider)volumeSlider.value=.8}updateVolumeIcon()});
window.buyAlbum=async function(id){const u='https://yoco-checkout.hyperproductionsa.workers.dev';console.log('🔵 Buy Album:',id);try{const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:id})});const d=await r.json();console.log('🔵 Response:',d);if(r.ok&&d.redirectUrl)window.location.href=d.redirectUrl;else alert('Payment error: '+(d.error||'Please try again.'))}catch(e){console.error('❌ Payment error:',e);alert('Payment error. Please try again.')}};
function updateCountdown(){if(!countdownOverlay)return;if(!countdownVisible){countdownOverlay.style.display='none';return}countdownOverlay.style.display='flex';const now=new Date(),diff=releaseDate-now;if(diff<=0){countdownOverlay.innerHTML=`<div style="color:#e5de69;font-size:2rem;margin-bottom:8px;"><i class="fas fa-check-circle"></i></div><div style="color:#e5de69;font-size:1rem;font-weight:700;background:#1e1d12;padding:6px 20px;border-radius:40px;border:2px solid #e5de69;margin-bottom:10px;">NOW AVAILABLE</div><h2 style="color:#fff;font-size:1.6rem;">HTs Collections V</h2><p style="color:#aaa;font-size:.85rem;margin:4px 0;">HyperSOUL-X · 2026 · 14 tracks</p>`;return}const d=Math.floor(diff/864e5),h=Math.floor(diff%864e5/36e5),m=Math.floor(diff%36e5/6e4),s=Math.floor(diff%6e4/1e3);if(cdDays)cdDays.textContent=String(d).padStart(2,'0');if(cdHours)cdHours.textContent=String(h).padStart(2,'0');if(cdMinutes)cdMinutes.textContent=String(m).padStart(2,'0');if(cdSeconds)cdSeconds.textContent=String(s).padStart(2,'0');if(csDate)csDate.textContent=releaseDate.toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'})}
function updateArtwork(a){if(!artImg||!countdownOverlay)return;if(a){artImg.src=getImage(a);countdownOverlay.style.display='none';countdownVisible=false;return}const d=allAlbums[4];artImg.src=getImage(d);countdownVisible=true;countdownOverlay.style.display='flex';updateCountdown()}
function updateBuyButton(a){if(!a){if(artBuyContainer){artBuyContainer.style.display='none';artBuyContainer.classList.add('hidden')}if(tlBuyBtn){tlBuyBtn.style.display='none';tlBuyBtn.classList.add('hidden')}return}if(artBuyContainer){artBuyContainer.style.display='flex';artBuyContainer.classList.remove('hidden');if(artBuyBtn)artBuyBtn.onclick=()=>buyAlbum(a.id);if(artBuyPrice)artBuyPrice.textContent='R150'}if(tlBuyBtn){tlBuyBtn.style.display='flex';tlBuyBtn.classList.remove('hidden');tlBuyBtn.onclick=()=>buyAlbum(a.id)}}
function updateNowPlaying(){if(!playingTrack||!playingAlbum){if(footerTitle)footerTitle.textContent='Select a track';if(footerArtist)footerArtist.textContent='—';if(pfTitle)pfTitle.textContent='Select a track';if(pfArtist)pfArtist.textContent='—';updateMobileText('Select a track','—');return}const t=playingTrack.mix?`${playingTrack.title} (${playingTrack.mix})`:playingTrack.title;if(footerTitle)footerTitle.textContent=t;if(footerArtist)footerArtist.textContent=playingTrack.artist;if(pfTitle)pfTitle.textContent=t;if(pfArtist)pfArtist.textContent=playingTrack.artist;updateMobileText(t,playingTrack.artist);const art=getImage(playingAlbum);if(footerArt)footerArt.src=art;if(pmArt)pmArt.src=art;if(pfArt)pfArt.src=art}
function updateMobileText(t,a){if(!pmTitle||!pmArtist)return;pmTitle.textContent=t||'Select a track';pmArtist.textContent=a||'—';pmTitle.classList.remove('scroll');void pmTitle.offsetWidth;if(pmTitle.scrollWidth>pmTitle.clientWidth)pmTitle.classList.add('scroll');pmArtist.classList.remove('scroll');void pmArtist.offsetWidth;if(pmArtist.scrollWidth>pmArtist.clientWidth)pmArtist.classList.add('scroll')}
function setupMediaSession(){if(!('mediaSession'in navigator)||!playingTrack||!playingAlbum)return;const t=playingTrack.mix?`${playingTrack.title} (${playingTrack.mix})`:playingTrack.title;navigator.mediaSession.metadata=new MediaMetadata({title:t,artist:playingTrack.artist,album:playingAlbum.title,artwork:[{src:getImage(playingAlbum),sizes:'512x512',type:'image/jpeg'}]});navigator.mediaSession.setActionHandler('play',()=>{audio.play();isPlaying=true;updatePlayBtn();startProgress()});navigator.mediaSession.setActionHandler('pause',()=>{audio.pause();isPlaying=false;updatePlayBtn();clearInterval(timer)});navigator.mediaSession.setActionHandler('previoustrack',()=>{if(playingAlbum)prevTrack()});navigator.mediaSession.setActionHandler('nexttrack',()=>{if(playingAlbum)nextTrack()})}
function showAlbumList(){if(albumList)albumList.style.display='flex';if(tracklistWrap)tracklistWrap.style.display='none';if(backBtn)backBtn.style.display='none';if(headerBadge){headerBadge.style.display='inline';headerBadge.textContent='5 albums'}if(tlBuyBtn)tlBuyBtn.style.display='none'}
function showTracklist(){if(albumList)albumList.style.display='none';if(tracklistWrap)tracklistWrap.style.display='flex';if(backBtn)backBtn.style.display='inline';if(headerBadge)headerBadge.style.display='none'}
function renderAlbums(){if(!albumList)return;const s=[...allAlbums].reverse();albumList.innerHTML=s.map(a=>{const i=allAlbums.indexOf(a),p=playingAlbum&&playingAlbum.id===a.id,h=albumStates[a.id]!==undefined;return`<div class="album-item" data-idx="${i}"><div class="ai-art"><img src="${getImage(a)}" alt="${a.title}" /></div><div class="ai-info"><div class="ai-title">${a.title} ${p?'▶':''} ${h&&!p?'●':''}</div><div class="ai-artist">${a.artist} · ${a.year}</div></div><div class="ai-cart" onclick="event.stopPropagation(); buyAlbum('${a.id}')" title="Buy album"><i class="fas fa-shopping-cart"></i></div><div class="ai-play"><i class="fas fa-play-circle"></i></div></div>`}).join('');albumList.querySelectorAll('.album-item').forEach(el=>{el.onclick=()=>loadAlbum(parseInt(el.dataset.idx))})}
function renderTracklist(a){if(!tracklistWrap||!tracklist)return;showTracklist();if(tlTitle)tlTitle.textContent=a.title;if(tlArtist)tlArtist.textContent=`${a.artist} · ${a.year}`;viewedAlbum=a;updateBuyButton(a);const st=albumStates[a.id],si=st?st.playingIdx:0;tracklist.innerHTML=a.tracks.map((t,i)=>{const sa=st&&i===si,ac=playingAlbum&&playingAlbum.id===a.id&&i===playingIdx,ti=t.mix?`${t.title} (${t.mix})`:t.title;return`<div class="track-item ${ac?'active':''}" data-idx="${i}"><div class="ti-play"><i class="fas ${ac?'fa-play-circle':'fa-play'}"></i></div><div class="ti-info"><div class="ti-title">${ti}</div><div class="ti-artist">${t.artist}</div></div><div class="ti-dur">${ac?'▶':(sa?'●':'♫')}</div></div>`}).join('');tracklist.querySelectorAll('.track-item:not(.locked)').forEach(el=>{el.onclick=()=>{const al=viewedAlbum;if(!al)return;playTrack(parseInt(el.dataset.idx),al)}})}
function loadAlbum(i){const a=allAlbums[i];viewedAlbum=a;updateArtwork(a);updateBuyButton(a);renderTracklist(a)}
function playTrack(i,a){if(!a)a=viewedAlbum;if(!a)return;const t=a.tracks[i];if(!t)return;playingAlbum=a;playingTrack=t;playingIdx=i;albumStates[a.id]={playingIdx:i};const u=getAudio(a,t);if(audio.src===u){if(isPlaying){audio.pause();isPlaying=false;clearInterval(timer);updatePlayBtn();return}else{audio.play().then(()=>{isPlaying=true;updatePlayBtn();startProgress()}).catch(e=>{console.warn('Playback blocked:',e);isPlaying=false;updatePlayBtn()});return}}audio.src=u;audio.load();updateNowPlaying();setupMediaSession();renderTracklist(a);renderAlbums();updateArtwork(a);audio.play().then(()=>{isPlaying=true;updatePlayBtn();startProgress()}).catch(e=>{console.warn('Playback blocked:',e);isPlaying=false;updatePlayBtn()})}
function togglePlay(){if(!playingTrack){if(viewedAlbum)playTrack(0,viewedAlbum);return}if(isPlaying){audio.pause();isPlaying=false;clearInterval(timer);updatePlayBtn()}else{audio.play().then(()=>{isPlaying=true;updatePlayBtn();startProgress()}).catch(e=>{console.warn('Playback blocked:',e);isPlaying=false;updatePlayBtn()})}}
function updatePlayBtn(){const i=isPlaying?'fa-pause-circle':'fa-play-circle';if(footerPlay)footerPlay.className=`fas ${i}`;if(pmPlay)pmPlay.className=`fas ${i}`;if(pfPlay)pfPlay.className=`fas ${i}`}
function startProgress(){clearInterval(timer);timer=setInterval(()=>{if(audio.duration&&!isNaN(audio.duration)){const p=audio.currentTime/audio.duration*100;if(footerFill)footerFill.style.width=p+'%';if(pfFill)pfFill.style.width=p+'%';const cm=Math.floor(audio.currentTime/60),cs=Math.floor(audio.currentTime%60),tm=Math.floor(audio.duration/60),ts=Math.floor(audio.duration%60);if(footerCur)footerCur.textContent=`${cm}:${String(cs).padStart(2,'0')}`;if(pfCur)pfCur.textContent=footerCur.textContent;if(footerTot)footerTot.textContent=`${tm}:${String(ts).padStart(2,'0')}`;if(pfTot)pfTot.textContent=footerTot.textContent}},200)}
function seekTo(e,p,f,c,t){const r=p.getBoundingClientRect(),x=Math.min(1,Math.max(0,(e.clientX-r.left)/r.width));if(audio.duration&&!isNaN(audio.duration)){audio.currentTime=x*audio.duration;f.style.width=x*100+'%';const cm=Math.floor(audio.currentTime/60),cs=Math.floor(audio.currentTime%60),tm=Math.floor(audio.duration/60),ts=Math.floor(audio.duration%60);c.textContent=`${cm}:${String(cs).padStart(2,'0')}`;t.textContent=`${tm}:${String(ts).padStart(2,'0')}`}}
function nextTrack(){if(!playingAlbum)return;const n=(playingIdx+1)%playingAlbum.tracks.length;albumStates[playingAlbum.id]={playingIdx:n};playTrack(n,playingAlbum)}
function prevTrack(){if(!playingAlbum)return;const p=(playingIdx-1+playingAlbum.tracks.length)%playingAlbum.tracks.length;albumStates[playingAlbum.id]={playingIdx:p};playTrack(p,playingAlbum)}
function goBack(){showAlbumList();updateArtwork(playingAlbum);if(artBuyContainer){artBuyContainer.style.display='none';artBuyContainer.classList.add('hidden')}if(tlBuyBtn){tlBuyBtn.style.display='none';tlBuyBtn.classList.add('hidden')}}
function openFull(){if(pf)pf.classList.add('active')}
function closeFull(){if(pf)pf.classList.remove('active')}
if(footerPlay)footerPlay.onclick=togglePlay;if(footerPrev)footerPrev.onclick=prevTrack;if(footerNext)footerNext.onclick=nextTrack;if(pmPlay)pmPlay.onclick=togglePlay;if(pmNext)pmNext.onclick=nextTrack;if(pmExpand)pmExpand.onclick=openFull;if(pfPlay)pfPlay.onclick=togglePlay;if(pfPrev)pfPrev.onclick=prevTrack;if(pfNext)pfNext.onclick=nextTrack;if(pfClose)pfClose.onclick=closeFull;if(backBtn)backBtn.onclick=goBack;audio.onended=nextTrack;
if(footerProgress)footerProgress.addEventListener('click',e=>seekTo(e,footerProgress,footerFill,footerCur,footerTot));
if(pfProgress)pfProgress.addEventListener('click',e=>seekTo(e,pfProgress,pfFill,pfCur,pfTot));
renderAlbums();showAlbumList();updateArtwork(null);updateMobileText('Select a track','—');
if(footerArt)footerArt.src=getImage(allAlbums[4]);if(pmArt)pmArt.src=getImage(allAlbums[4]);
if(artBuyContainer){artBuyContainer.style.display='none';artBuyContainer.classList.add('hidden')}
if(tlBuyBtn){tlBuyBtn.style.display='none';tlBuyBtn.classList.add('hidden')}
updateCountdown();setInterval(updateCountdown,1e3);updateVolumeIcon();
const main=document.getElementById('main'),pcFooter=document.getElementById('pcFooter'),mobileFooter=document.getElementById('playerMobile');
function handleResize(){const m=window.innerWidth<=860;if(main)main.style.flexDirection=m?'column':'row';if(pcFooter)pcFooter.style.display=m?'none':'flex';if(mobileFooter)mobileFooter.style.display=m?'flex':'none';updateArtwork(playingAlbum)}
handleResize();window.addEventListener('resize',handleResize);
})(); 
